
/* This file is generated by glib-mkenums, do not modify it. This code is licensed under the same license as the containing project. Note that it links to GLib, so must comply with the LGPL linking clauses. */

#include "config.h"
#include "gdk-pixbuf-enum-types.h"
#include "gdk-pixbuf-core.h "
/* enumerations from "D:/Projects/AAAAAAAAA/glib/__builddir/../gio/gioenums.h" */
GType
gdk_colorspace_get_type (void)
{
  static GType g_define_type_id__volatile = 0;

  if (g_once_init_enter_pointer (&g_define_type_id__volatile))
    {
      static const GFlagsValue values[] = {
        { GDK_COLORSPACE_RGB, "GDK_COLORSPACE_RGB", "RGB" },
        { 0, NULL, NULL }
      };
      GType g_define_type_id =
        g_flags_register_static (g_intern_static_string ("GdkColorspace"), values);
      g_once_init_leave (&g_define_type_id__volatile, g_define_type_id);
    }

  return g_define_type_id__volatile;
}

/* Generated data ends here */
